# Generated by Django 4.2.11 on 2025-03-18 09:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('verse_fetcher', '0001_initial'),
        ('web_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('comment', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_authored', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_comments', to='verse_fetcher.books')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verse_comments', to='verse_fetcher.verses')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'indexes': [models.Index(fields=['author'], name='web_page_co_author__a096dc_idx'), models.Index(fields=['book'], name='web_page_co_book_id_c707c3_idx'), models.Index(fields=['verse'], name='web_page_co_verse_i_2debcb_idx')],
                'unique_together': {('author', 'verse')},
            },
        ),
    ]
