# Generated by Django 4.2.11 on 2025-03-20 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('verse_fetcher', '0001_initial'),
        ('web_page', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks_authored', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_bookmarks', to='verse_fetcher.books')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verse_bookmarks', to='verse_fetcher.verses')),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'indexes': [models.Index(fields=['author'], name='web_page_bo_author__011021_idx'), models.Index(fields=['book'], name='web_page_bo_book_id_9de036_idx'), models.Index(fields=['verse'], name='web_page_bo_verse_i_6f9b79_idx')],
                'unique_together': {('author', 'verse')},
            },
        ),
    ]
