# Generated by Django 4.2.11 on 2025-04-01 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('verse_fetcher', '0001_initial'),
        ('web_page', '0003_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_read', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_read_by', to='verse_fetcher.books')),
            ],
            options={
                'verbose_name': 'ReadBook',
                'verbose_name_plural': 'ReadBooks',
                'indexes': [models.Index(fields=['author'], name='web_page_re_author__958c6b_idx'), models.Index(fields=['book'], name='web_page_re_book_id_29ed25_idx')],
                'unique_together': {('author', 'book')},
            },
        ),
    ]
