# Generated by Django 4.2.11 on 2025-04-23 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('verse_fetcher', '0002_alter_verses_options'),
        ('web_page', '0004_readbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('start_offset', models.PositiveIntegerField()),
                ('end_offset', models.PositiveIntegerField()),
                ('highlighted_text', models.TextField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verse_fetcher.books')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verse_fetcher.verses')),
            ],
            options={
                'unique_together': {('author', 'verse', 'start_offset', 'end_offset')},
            },
        ),
    ]
