# Generated by Django 4.2.11 on 2025-03-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acronym', models.TextField()),
                ('title', models.TextField()),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Verses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter', models.IntegerField()),
                ('verse_number', models.IntegerField()),
                ('verse', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'verses',
                'ordering': ['chapter', 'verse_number'],
                'managed': False,
            },
        ),
    ]
