# Generated by Django 4.2.11 on 2025-04-23 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verse_fetcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verses',
            options={'managed': False, 'ordering': ['book', 'chapter', 'verse_number']},
        ),
    ]
